# Generated by Django 4.1.5 on 2023-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haversine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='place',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
    ]
