# Generated by Django 4.1.5 on 2023-01-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haversine', '0002_position_place_alter_position_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='latitude_two',
            field=models.DecimalField(decimal_places=8, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='longitude_two',
            field=models.DecimalField(decimal_places=8, max_digits=26, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='place_two',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
