# Generated by Django 4.1.5 on 2023-01-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haversine', '0004_remove_position_latitude_two_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='place_one',
        ),
        migrations.AddField(
            model_name='place',
            name='location_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_two', to='haversine.position'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_two',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
