# Generated by Django 4.1.5 on 2023-01-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haversine', '0005_rename_place_place_place_one_place_location_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='latitude_two',
            field=models.DecimalField(decimal_places=8, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='longitude_two',
            field=models.DecimalField(decimal_places=8, max_digits=26, null=True),
        ),
    ]
